---
- name: Make sure desired packages are installed
  openbsd_pkg:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_list_openbsd + packages_list | default([]) }}"
  tags:
    - pkg

- name: "Install PIP packages.."
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_pip_list_openbsd + packages_pip_list | default([]) }}"
  tags:
    - pip

