---
- name: Make sure desired packages are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages_list_redhat }}"
    - "{{ packages_list }}"
  tags:
    - pkg

- name: "Install PIP packages.."
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages_pip_list_redhat }}"
    - "{{ packages_pip_list | default(omit) }}"
  tags:
    - pip

